### PR TITLE
Detecting environment for macOS

### PR DESCRIPTION
**Pull request by bmourat**

### CODE REVIEW

**Comment by jaelim-ms** [comment]
Looks good to me but we need to update OSS since this implementation contains 3rd party implementation.

**Comment by TroubleMakerBen** [comment]
@bmourat please add the copyright information to the 3rd party license document.

**Comment by TroubleMakerBen** [comment]
We need to register the component, I'm creating a task for that.

**Comment by TroubleMakerBen** [comment]
We've discussed this issue. I don't think we need to detect a MAS environment (HA didn't). And the detection mechanism in this PR doesn't look like it's gonna work reliably.
To detect a MAS environment, we'd need to 
a) check for a sandbox environment
b) check if the app was signed with a cert by apple (an app can be outside of the MAS but be sandboxed)
c) possibly do more?

In the end, we're closing this PR. If the need arises to detect the MAS as an environment, we'll create a new task and look into how we can detect the MAS reliably (and of course verify).

**Pull request closed without merging**
