### PR TITLE
Test frameworks for tvOS added.

### PR DESCRIPTION
**Pull request by bmourat**
OCHamcrest and OCMockito for tvOS 10.0 added to Vendor folder.
Instructions and scripts for building added to Scripts folder.

### CODE REVIEW

**Comment by bmourat** [comment]
No reason at all, we just were discussing this two libraries with @TroubleMakerBen

**Comment by TroubleMakerBen** [comment]
Sorry, I missed that HockeyApp and Mobile Center are not using the same Mocking framework. 🙈
We should keep using `OCMock` for Mobile Center. Can you @bmourat go ahead and build OCMock for tvOS instead of OCMockito?

**Comment by bmourat** [comment]
Yes, sure

**Comment by jaelim-ms** [comment]
#647 contains the libraries for tvOS. You also need to add OHHttpStubs

**Comment by jaelim-ms** [comment]
#698 replaces this PR. Closing this one.

**Pull request closed without merging**
